Resources:
  PrometheusAssumeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - "arn:aws-us-gov:iam::{ACCOUNTID}:root"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws-us-gov:iam::aws:policy/AmazonEC2ReadOnlyAccess"