#
#
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
#
#
version: '3.8'
services:
    pushgateway:
        container_name: pushgateway
        network_mode: host
        pid: host
        restart: unless-stopped
        image: prom/pushgateway
    prometheus-node-exporter:
        container_name: node-exporter
        network_mode: host
        pid: host
        restart: unless-stopped
        volumes:
            - '/:/host:ro,rslave'
        image: quay.io/prometheus/node-exporter
        command:
            - '--path.rootfs=/host'
volumes:
    prometheus-data:
    grafana-data:
