{
 "title": "ParallelCluster Summary",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "cluster", "query": { "query": "label_values(cluster)" } },
   {
    "name": "headnode_instance",
    "query": {
     "query": "label_values({cluster=\"$cluster\", nodetype=\"HeadNode\"},instance_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cluster Storage",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance_id=\"$headnode_instance\",fstype=~\"ext4|xfs|lustre|nfs|nfs4\"}-0"
    },
    {
     "expr": "node_filesystem_avail_bytes {instance_id=\"$headnode_instance\",fstype=~\"ext4|xfs|lustre|nfs|nfs4\"}-0"
    },
    {
     "expr": "1-(node_filesystem_free_bytes{instance_id=\"$headnode_instance\",fstype=~\"ext4|xfs|lustre|nfs|nfs4\"} / node_filesystem_size_bytes{instance_id=\"$headnode_instance\",fstype=~\"ext4|xfs|lustre|nfs|nfs4\"})"
    }
   ]
  },
  {
   "title": "CPU, Memory & Disk Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total CPU cores",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{mode=\"idle\",cluster=\"$cluster\",instance_id!=\"$headnode_instance\"})"
    }
   ]
  },
  {
   "title": "Avg. CPU cores",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{mode=\"idle\",cluster=\"$cluster\",instance_id!=\"$headnode_instance\"})/count(count(node_cpu_seconds_total{cluster=\"$cluster\",instance_id!=\"$headnode_instance\"}) by (instance_id))"
    }
   ]
  },
  {
   "title": "Total CPU use",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\",cluster=\"$cluster\",instance_id!=\"$headnode_instance\"}[1m]))"
    }
   ]
  },
  {
   "title": "Avg. CPU use",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\",cluster=\"$cluster\",instance_id!=\"$headnode_instance\"}[1m]))/count(count(node_cpu_seconds_total{cluster=\"$cluster\",instance_id!=\"$headnode_instance\"}) by (instance_id))"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{cluster=\"$cluster\",instance_id!=\"$headnode_instance\"})"
    }
   ]
  },
  {
   "title": "Avg. Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{cluster=\"$cluster\",instance_id!=\"$headnode_instance\"})/count(node_memory_MemTotal_bytes{cluster=\"$cluster\",instance_id!=\"$headnode_instance\"})"
    }
   ]
  },
  {
   "title": "Total Memory use",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{cluster=\"$cluster\",instance_id!=\"$headnode_instance\"}) - sum(node_memory_MemAvailable_bytes{cluster=\"$cluster\",instance_id!=\"$headnode_instance\"})"
    }
   ]
  },
  {
   "title": "Avg. Memory use",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal_bytes{cluster=\"$cluster\",instance_id!=\"$headnode_instance\"}) - sum(node_memory_MemAvailable_bytes{cluster=\"$cluster\",instance_id!=\"$headnode_instance\"}))/count(node_memory_MemTotal_bytes{cluster=\"$cluster\",instance_id!=\"$headnode_instance\"})"
    }
   ]
  },
  {
   "title": "Total Disk (write)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_written_bytes_total{cluster=\"$cluster\",instance_id!=\"$headnode_instance\"}[1m]))"
    }
   ]
  },
  {
   "title": "Avg. Disk (write)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_written_bytes_total{cluster=\"$cluster\",instance_id!=\"$headnode_instance\"}[1m])) / count(node_disk_written_bytes_total{cluster=\"$cluster\",instance_id!=\"$headnode_instance\"})"
    }
   ]
  },
  {
   "title": "Total Disk (read)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{cluster=\"$cluster\",instance_id!=\"$headnode_instance\"}[1m]))"
    }
   ]
  },
  {
   "title": "Avg. Disk (read)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{cluster=\"$cluster\",instance_id!=\"$headnode_instance\"}[1m])) / count(node_disk_read_bytes_total{cluster=\"$cluster\",instance_id!=\"$headnode_instance\"})"
    }
   ]
  },
  {
   "title": "CPU load",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{mode=\"idle\",cluster=\"$cluster\",instance_id!=\"$headnode_instance\"})",
     "legendFormat": "Total cores"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\",cluster=\"$cluster\",instance_id!=\"$headnode_instance\"}[1m]))",
     "legendFormat": "Load in cores"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{cluster=\"$cluster\",instance_id!=\"$headnode_instance\"})",
     "legendFormat": "Total Memory"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes{cluster=\"$cluster\",instance_id!=\"$headnode_instance\"}) - sum(node_memory_MemAvailable_bytes{cluster=\"$cluster\",instance_id!=\"$headnode_instance\"})",
     "legendFormat": "Used Memory"
    }
   ]
  },
  {
   "title": "Disk I/O (read)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{cluster=\"$cluster\",instance_id!=\"$headnode_instance\"}[1m]))",
     "legendFormat": "Read throughput"
    }
   ]
  },
  {
   "title": "Disk I/O (write)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_written_bytes_total{cluster=\"$cluster\",instance_id!=\"$headnode_instance\"}[1m]))",
     "legendFormat": "Write throughput"
    }
   ]
  },
  {
   "title": "Network Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Current Total Throughput (Transmit)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(irate(node_network_transmit_bytes_total{device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*',cluster=\"$cluster\",instance_id!=\"$headnode_instance\"}[1m]))"
    }
   ]
  },
  {
   "title": "Current Avg. Throughput per Node (Transmit)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(irate(node_network_transmit_bytes_total{device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*',cluster=\"$cluster\",instance_id!=\"$headnode_instance\"}[1m]))/count(count(node_network_transmit_bytes_total{cluster=\"$cluster\",instance_id!=\"$headnode_instance\"}) by(instance_id))"
    }
   ]
  },
  {
   "title": "Current Total Throughput (Receive)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_bytes_total{device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*',cluster=\"$cluster\",instance_id!=\"$headnode_instance\"}[1m]))"
    }
   ]
  },
  {
   "title": "Current Avg. Throughput per Node (Receive)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_bytes_total{device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*',}[1m]))/count(count(node_network_receive_bytes_total{cluster=\"$cluster\",instance_id!=\"$headnode_instance\"}) by(instance_id))"
    }
   ]
  },
  {
   "title": "Throughput (Transmit)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_network_transmit_bytes_total{device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*',cluster=\"$cluster\",instance_id!=\"$headnode_instance\"}[1m]))",
     "legendFormat": "Transmit"
    }
   ]
  },
  {
   "title": "Throughput (Receive)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_bytes_total{device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*',cluster=\"$cluster\",instance_id!=\"$headnode_instance\"}[1m]))",
     "legendFormat": "Receive"
    }
   ]
  }
 ]
}