{
 "title": "Slurm Summary",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Scheduler Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Slurm Jobs",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "slurm_queue_running", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Jobs",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 9, "x": 4, "y": 1 },
   "targets": [
    { "expr": "slurm_queue_completing", "legendFormat": "Completing Jobs" },
    { "expr": "slurm_queue_running", "legendFormat": "Running Jobs" },
    { "expr": "slurm_queue_pending", "legendFormat": "Pending Jobs" },
    { "expr": "slurm_queue_completed", "legendFormat": "Completed Jobs" },
    { "expr": "slurm_queue_timeout", "legendFormat": "Timed out Jobs" },
    { "expr": "slurm_queue_failed", "legendFormat": "Failed Jobs" },
    { "expr": "slurm_queue_node_fail", "legendFormat": "Failed jobs (due to NodeFail)" },
    { "expr": "slurm_queue_suspended", "legendFormat": "Suspended Jobs" },
    { "expr": "slurm_queue_cancelled", "legendFormat": "Cancelled Jobs" },
    { "expr": "slurm_queue_preempted", "legendFormat": "Preempted Jobs" },
    {
     "expr": "slurm_queue_completing + slurm_queue_running + slurm_queue_pending + slurm_queue_completed + slurm_queue_timeout + slurm_queue_failed + slurm_queue_node_fail + slurm_queue_suspended + slurm_queue_cancelled + slurm_queue_preempted",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 11, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "slurm_nodes_alloc", "legendFormat": "Allocated Nodes" },
    { "expr": "slurm_nodes_comp", "legendFormat": "Completing Nodes" },
    { "expr": "slurm_nodes_idle", "legendFormat": "Idle Nodes" },
    { "expr": "slurm_nodes_mix", "legendFormat": "Mixed Nodes" },
    { "expr": "slurm_nodes_down", "legendFormat": "Down Nodes" },
    { "expr": "slurm_nodes_drain", "legendFormat": "Draining Nodes" },
    { "expr": "slurm_nodes_err", "legendFormat": "Nodes in *error* state" },
    { "expr": "slurm_nodes_fail", "legendFormat": "Nodes in *fail* state" },
    {
     "expr": "slurm_nodes_alloc + slurm_nodes_down + slurm_nodes_drain + slurm_nodes_idle + slurm_nodes_mix + slurm_nodes_comp + slurm_nodes_maint",
     "legendFormat": "Total Nodes"
    }
   ]
  },
  {
   "title": "Slurm Pending Jobs",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "slurm_queue_pending", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Allocated CPUs",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 9, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "slurm_cpus_alloc", "legendFormat": "CPUs Allocated" }
   ]
  },
  {
   "title": "Allocated GPUs",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 9, "x": 9, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "slurm_gpus_alloc", "legendFormat": "GPUs Allocated" }
   ]
  }
 ]
}